export enum TeamType {
  ITNS_DISTRIBUTION = 'ITNS_DISTRIBUTION',

  ITNS_WAREHOUSE = 'ITNS_WAREHOUSE',

  IRS_DISTRIBUTION = 'IRS_DISTRIBUTION',

  IRS_WAREHOUSE = 'IRS_WAREHOUSE',

  CHV_PATIENTS = 'CHV_PATIENTS',
}
